version: '3.8'
services:
  frontend:
    build:
      context: ./jewelry-store
      dockerfile: Dockerfile
    image: $
    container_name: ${imagenamefrontend}
    ports:
      - "3000:80"   # Host:Container (Host 3000 → Container 80 for Nginx)
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8000/api
      - REACT_APP_AUTH_BASE_URL=http://auth:8001
      - REACT_APP_BACKEND_HOST=backend
      - REACT_APP_BACKEND_PORT=8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${imagenamebackend}
    container_name: jewelry-backend
    ports:
      - "8000:8000"
    depends_on:
      - auth
    environment:
      - AUTH_SERVICE_URL=http://auth:8001
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: ${imagenameauth}
    container_name: jewelry-auth
    ports:
      - "8001:8001"
    environment:
      - WT_SECRET_KEY=${JWT_SECRET_KEY}

 